name: bose_music_app
description: Simple local MP3 player for internship assignment
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.0
  audioplayers: ^5.2.1
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  id3: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.webp"